import type { MarketStore } from "../types/market"

const now = new Date().toISOString()

export const defaultMarketStores: readonly MarketStore[] = [
  {
    id: "hetras_seongsu",
    nameKo: "헤트라스 성수",
    nameZh: "Hetras 圣水",
    categoryKo: "향/라이프스타일",
    categoryZh: "香氛/生活方式",
    monthlyRevenue: 1500000000,
    peakMonthlyRevenue: 1800000000,
    avgOrderValue: 50000,
    conversion: 20,
    margin: 65,
    noteKo: "월 방문객 150,000명 기준의 성수권 고매출 사례",
    noteZh: "以月访客 150,000 人为基准的圣水高销售案例",
    updatedAt: now,
    isDeleted: false,
  },
  {
    id: "salt_bread",
    nameKo: "자연도 소금빵",
    nameZh: "自然岛盐面包",
    categoryKo: "디저트/베이커리",
    categoryZh: "甜点/烘焙",
    monthlyRevenue: 420000000,
    peakMonthlyRevenue: 620000000,
    avgOrderValue: 16000,
    conversion: 18,
    margin: 58,
    noteKo: "회전율과 줄서기 효과가 큰 베이커리형 매장",
    noteZh: "周转率与排队效应明显的烘焙店型",
    updatedAt: now,
    isDeleted: false,
  },
  {
    id: "dessert_bakery",
    nameKo: "성수 디저트/베이커리형",
    nameZh: "圣水甜点/烘焙型",
    categoryKo: "F&B",
    categoryZh: "餐饮",
    monthlyRevenue: 250000000,
    peakMonthlyRevenue: 380000000,
    avgOrderValue: 22000,
    conversion: 14,
    margin: 55,
    noteKo: "체류보다 구매 회전이 중요한 표준 비교군",
    noteZh: "购买周转比停留更关键的标准对照组",
    updatedAt: now,
    isDeleted: false,
  },
  {
    id: "beauty_flagship",
    nameKo: "뷰티 플래그십/체험형",
    nameZh: "美妆旗舰/体验型",
    categoryKo: "뷰티",
    categoryZh: "美妆",
    monthlyRevenue: 520000000,
    peakMonthlyRevenue: 760000000,
    avgOrderValue: 68000,
    conversion: 10,
    margin: 68,
    noteKo: "체험 후 구매 전환이 핵심인 고마진 매장",
    noteZh: "体验后转化购买是核心的高毛利门店",
    updatedAt: now,
    isDeleted: false,
  },
  {
    id: "lifestyle_goods",
    nameKo: "잡화/라이프스타일형",
    nameZh: "杂货/生活方式型",
    categoryKo: "리테일",
    categoryZh: "零售",
    monthlyRevenue: 180000000,
    peakMonthlyRevenue: 260000000,
    avgOrderValue: 36000,
    conversion: 9,
    margin: 52,
    noteKo: "객단가와 재방문율이 동시에 필요한 비교군",
    noteZh: "客单价与复访率都重要的对照组",
    updatedAt: now,
    isDeleted: false,
  },
  {
    id: "linkland_current",
    nameKo: "링크랜드 현재 가정",
    nameZh: "Linkland 当前假设",
    categoryKo: "임차 투자 가정",
    categoryZh: "租赁投资假设",
    monthlyRevenue: 60000000,
    peakMonthlyRevenue: 90000000,
    avgOrderValue: 50000,
    conversion: 0.8,
    margin: 62,
    noteKo: "현재 계산기 기본 오프라인 매출 가정",
    noteZh: "当前计算器默认线下销售假设",
    updatedAt: now,
    isDeleted: false,
  },
]
